name: CMake

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DBUILD_TESTING=On -DBUILD_EXAMPLE=On -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
      
    - name: Code Coverage
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make coverage && cat coverage.xml
      
    - name: Upload Code Coverage Reports to CodeCov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{runner.workspace}}/build
        path_to_write_report: ${{runner.workspace}}/coverage
        flags: unittests
        name: LinkedList
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: Coverage Report
        path: ${{runner.workspace}}/coverage
